# Generated by Django 2.2.3 on 2019-07-31 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
    ]
