# Generated by Django 2.2.3 on 2019-08-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_question_module'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='QuestionChoices',
            unique_together={('question', 'choice')},
        ),
    ]
