# Generated by Django 2.2.3 on 2019-08-01 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20190801_0709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentquestionanswer',
            unique_together={('student', 'question')},
        ),
    ]
